### ISSUE TITLE
fetch() error does not return dataset

### ISSUE THREAD

**Issue by gleasocd** [domoinc-r/DomoR#1]
DomoR fetch() function does not return the identified dataset. The same error message seems to appear for all datasets regardless of displayType (dataflow, datafusion, etc.)

```
df <- DomoR::fetch(1)
# Error in readr::read_csv(x, locale = readr::locale(encoding = encoding),  : 
# unused arguments (check.names = FALSE, na.strings = "\\N", colClasses = c(NA, NA))
```

**Comment by nareshkp** [comment]
Released new version.
