### ISSUE TITLE
Installation instructions - don't need auth token when downloading and installing

### ISSUE THREAD

**Issue by j450h1** [domoinc-r/DomoR#11]
Hi there, 

I think this ```, auth_token="<auth_token>"`` part is unnecessary from here:
```
Installation method from GitHub
You can install directly from our private Github repository:

install_github(repo="domoinc-r/DomoR", auth_token="<auth_token>")
```

When most people are used to this and it works fine without specifying the auth token. Perhaps this simpler method could be provided as an alternative to not confuse people who don't specify auth_token as you specify

```
install_github(repo="domoinc-r/DomoR")
```

**Comment by nareshkp** [comment]
Handled in the latest release (Release Version 1.7). Thank you
