### ISSUE TITLE
DomoR installation issue

### ISSUE THREAD

**Issue by debashis1982** [domoinc-r/DomoR#19]
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Installing DomoR's latest commit **c2bc1d6a87b3475974114e40b25e9982aceff7cb** is failing.
```
install_github(repo="domoinc-r/DomoR")
```
throws error
```
Error in parse(outFile) : 
  /tmp/RtmppmX8GO/R.INSTALL856881d54e/DomoR/R/replace_ds.R:172:18: unexpected symbol
171: lookup_stream <- function (dataset_id) {
172:   search_stream('dataSource.id
```
Installing the previous commit works fine.
```
install_github(repo="domoinc-r/DomoR@d3b659602565bf0f676f57481a6445d3fea41f41")
```

**Comment by nareshkp** [comment]
@debashis1982 Fixed in the new release
