### ISSUE TITLE
Write Data to Disk

### ISSUE THREAD

**Issue by ries9112** [domoinc-r/DomoR#23]
Hello, is there a way of writing the data to disk and avoid memory issues relating to the RAM?

When I use the `fetch_to_disk()` function the data gets written to disk, but it still runs into memory allocation limits relating to the RAM instead of the disk:
![image](https://user-images.githubusercontent.com/32306488/99568382-952f5700-298c-11eb-8a77-fac6761618ec.png)

Does anyone have a solution to this that enables to write a .csv file to disk directly and not the RAM? Or batch the writing of the file so it avoids running into this issue?

Would really appreciate any help figuring out how to export a really large dataset to disk!

**Comment by jimmyg3g** [comment]
Checkout Domo's Java CLI, more info in my last comment here:
https://github.com/domoinc-r/DomoR/issues/8#issuecomment-729942071](https://github.com/domoinc-r/DomoR/issues/8#issuecomment-729942071)

**Comment by ries9112** [comment]
Thank you for both responses @jimmyg3g. I am still unclear on what was causing me to run into this problem, but when using `fetch_to_disk()` exactly as outlined I am no longer running into this issue and successfully wrote files of 30+GB as temp files and I am able to successfully iterate through the data in batches of 100k rows at a time.

So all good here and I was able to resolve my issue, unfortunately I don't have any insights as to what changed here. Thank you for the suggestion!
