### ISSUE TITLE
Limit Data Fetch to Pull first N Rows

### ISSUE THREAD

**Issue by revolutionbruin** [domoinc-r/DomoR#4]
Would be very useful if the fetch command did not have to pull the full data set into memory but allowed a preview of the data to be fetched.

**Comment by jimmyg3g** [comment]
On version 1.8, `fetch_to_disk` has an nrows parameter.

**Comment by nareshkp** [comment]
@revolutionbruin fetch_to_disk has an option to specify the nrows parameter
